### ISSUE TITLE
What should happen in case a deposit transfer fails on the destination chain?

### ISSUE THREAD

**Issue by mialbu** [bane-labs/bridge-evm-contracts#11]
If a transfer fails (i.e., `send` returns `false`), what should the process of handling it be like?

AFAIK the following are the only cases for a failing `send` execution on contract level:
- insufficient funds -> should not be a problem for our native bridge contract on Bane.
- policy block of receiving address -> if an address is blocked by policy, is it also blocked from receiving assets?

If there aren't any other cases, imo, we could ignore the result of `send()`, i.e., directly use `transfer()`.

Otherwise, here are some ideas:
- emit `FailedDeposit` and handle these cases manually, e.g. refund executed by the owner on the originating chain (minus a fee deduction)
- ignore it -> user's responsibility
- directly invoking the reversal method - on deposit verification -> invoke withdrawal when send fails?

**Comment by cloud8little** [comment]
why insufficient funds should not be a problem for our native bridge contract on Bane?

**Comment by mialbu** [comment]
Depends on how Bane will be initialized. When I was writing this comment, the preferred way was that the native bridge contract holds all gas that could ever exist on Bane (except for some allocation to relayer and validators). There are other ways to do it, but afaik we will not have a mint function for gas, but just initial balances defined in the genesis allocation.
@cloud8little

**Comment by mialbu** [comment]
If a recipient address is a contract or a transfer fails, the deposit is added to be claimable.
