### ISSUE TITLE
NBE-12 - Wrong event emit `[Low]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#112]
The events emitted during the execution of the `lock` and `unlock` methods of the `BridgeImpl` contract are incorrect. Due to human error, these events are executed in the opposite method that they are intended to represent. This misalignment can lead to dApps or users, that are attached to these events, to react according to the blocking and unlocking of the contract to function inappropriately.

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/45d99c3c-c7ae-4c21-a0b2-0bc9d0e7e05a)
_Events emitted in reverse_

**Source references:**
- https://github.com/bane-labs/bridge-evm-contracts/blob/1fc995f9c158a9948d5c2008db9773c9c81b2bfd/contracts/BridgeImpl.sol#L185-L193

**Remediation:**
- Swap both events so that they are emitted in the correct methods.

**Comment by mialbu** [comment]
The lock events have been renamed to pause in the meantime and the following is now the current state. I think it's correct now.

### Pausing of all Bridges

https://github.com/bane-labs/bridge-evm-contracts/blob/228169d98d16b094a5cbeada9c6de6ee3b707255/contracts/bridge/BridgeImpl.sol#L26-L34

### Pausing of the Gas Bridge

https://github.com/bane-labs/bridge-evm-contracts/blob/228169d98d16b094a5cbeada9c6de6ee3b707255/contracts/bridge/BridgeImpl.sol#L38-L56

### Pausing of Token Bridges

https://github.com/bane-labs/bridge-evm-contracts/blob/228169d98d16b094a5cbeada9c6de6ee3b707255/contracts/bridge/BridgeImpl.sol#L263-L279

**Comment by mialbu** [comment]
Nvm, actually I just saw that `unpauseTokenBridge` emits a wrong event. I'll fix it.

**Comment by mialbu** [comment]
Fixed in #113.
