### ISSUE TITLE
What should happen if a deposit address is a contract?

### ISSUE THREAD

**Issue by mialbu** [bane-labs/bridge-evm-contracts#12]
The native bridge won't support contracts receiving deposits or withdrawals. However, the originating bridge contract cannot verify that the recipient address is an externally owned account (EOA). Thus, it will also accept deposits/withdrawals that have a contract address as recipient.

As one might assume there could be cases where someone wants to bridge GAS to a contract on the destination chain. Even though they shouldn't and even if BaneLabs provides extensive docs, we shouldn't ignore that there will be someone out there who does exactly that anyways. How should this be handled on contract level on the destination chain?

In the current implementation, if the recipient of a deposit/withdrawal proof is a contract, no funds are sent and no further execution happens regarding it.

What should happen in that case? Similar to #11, there are two ideas from my side:
- emit FailedDeposit and handle these cases manually, e.g. refund executed by the owner on the originating chain (minus a fee deduction)
- ignore it -> user's responsibility
- directly invoking the reversal method - on deposit verification -> invoke withdrawal when send fails?

**Comment by cloud8little** [comment]
I think this issue has been solved.  can we close this now? @mialbu

**Comment by mialbu** [comment]
Yes, this has been decided. The deposit is added to be claimable if the recipient address is a contract, as well as if the transfer is unsuccessful.
