### ISSUE TITLE
how does the rootMap in withdraw work

### ISSUE THREAD

**Issue by cloud8little** [bane-labs/bridge-evm-contracts#16]
According to the current logic, with subsequent withdraw nonce, rootMap will be like the following graph, seems it doesn't look like a root map.  when withdraw nonce is 1, it makes sense the root is the hash of the withdraw data.  when nonce is 2, it stores only the hash of (node1, node2), which is actually the root. when nonce is 3, it becomes confusing on how the rootMap looks like.  the question is how the rootMap works in the whole deposit and withdraw logic.

![d0d0148d23c13cad7da285d5863e86f](https://github.com/bane-labs/bridge-evm-contracts/assets/34291844/6908dcd2-a19b-4e6f-8afd-9a21e09a9bc9)

**Comment by mialbu** [comment]
You're absolutely right. I mixed up the order of updating the maxDepth. I'll fix it.

The problem was adding 1 after the `maxDepth` has already been incremented:

```solidity
maxDepth += 1;
rootMap[maxDepth + 1] = right;
```

It should look like this:

```solidity
maxDepth += 1;
rootMap[maxDepth] = right;
```
