### ISSUE TITLE
[Bridge Bane] Use path for proof verification

### ISSUE THREAD

**Issue by mialbu** [bane-labs/bridge-evm-contracts#17]
Currently the merkle tree proof is always done from the right to the left. In order to prepare for implementing a claim functionality which requires any leaf to be verified to the root, the contract should use a path in the verification.

- [x] Validators should only sign the concatenation of the top root and the last nonce and not the concatenation of the roots of all deposits.
- [x] Use a bit map to provide a path for the proof verification.

**Comment by cloud8little** [comment]
So all deposit users will use path for proof verification?

**Comment by mialbu** [comment]
Hey @cloud8little, yes, all deposit proofs will need a path.

The relayer will still be in charge of executing the deposits and distribute the funds. However, there are some deposit cases that could happen where the funds are not distributed on the destination chain. For example, if the recipient address is a contract, or if `send` returns `false`.

After some discussion with @txhsl, @steven1227 and @gsmachado in Hong Kong, we think it's good to have a claim method for these cases. Now, in order to allow claiming, the contract needs to provide a verification method where a path can be provided. I think it's best if we have **one single merkle proof verification method** and not one with and one without a path.

**Comment by txhsl** [comment]
> Hey @cloud8little, yes, all deposit proofs will need a path.
> 
> The relayer will still be in charge of executing the deposits and distribute the funds. However, there are some deposit cases that could happen where the funds are not distributed on the destination chain. For example, if the recipient address is a contract, or if in the `transfer` returns `false`.
> 
> After some discussion with @txhsl, @steven1227 and @gsmachado in Hong Kong, we think it's good to have a claim method for these cases. Now, in order to allow claiming, the contract needs to provide a verification method where a path can be provided. I think it's best if we have **one single merkle proof verification method** and not one with and one without a path.

It could not always be the `right` if we are using an SMT like [Plasma](https://github.com/ethereum-plasma/plasma/blob/master/contracts/PlasmaChainManager.sol#L236) with a fixed depth. I think there is something different from the beginning. Is our current EVM bridge using a dynamic-depth tree?

**Comment by mialbu** [comment]
> It could not always be the `right` if we are using an SMT like [Plasma](https://github.com/ethereum-plasma/plasma/blob/master/contracts/PlasmaChainManager.sol#L236) with a fixed depth. I think there is something different from the beginning. Is our current EVM bridge using a dynamic-depth tree?

We're using a dynamic-depth tree, yes.

**Comment by mialbu** [comment]
What do you mean with `I think there is something different from the beginning`? @txhsl

**Comment by txhsl** [comment]
> What do you mean with `I think there is something different from the beginning`? @txhsl

Maybe SMT is better for gas optimization? The gas cost is stable and many preloaded zero hash. I may need some more reading or calculation to give a convincing conclusion.

**Comment by txhsl** [comment]
> We're using a dynamic-depth tree, yes.

I found it was ZK-related bridges/rollups that use fixed-depth trees, because they use fixed-size ZK circuits, which require fixed-size parameters. So I'm OK with dynamic-depth tree now, but I read the code implementation of the EVM contract, the tree depth increases whenever a new deposit/withdraw comes, or we can say the `nonce` increases. There are two new questions,

1. Will the proof size increase very fast, so transaction becomes bigger and bigger?
2. Will the proof verification loop increase very fast and easily break the EVM stack limit?

**Comment by mialbu** [comment]
I'll close this issue. We've been discussing many things through Discord.
