### ISSUE TITLE
[Consideration] Set contract owner to a multi-sig contract or use governance

### ISSUE THREAD

**Issue by txhsl** [bane-labs/bridge-evm-contracts#176]
Currently, the bridge management contract is using an OZ's `Ownable2StepUpgradeable` library to maintain an `owner` role for `onlyOwner` modified methods. We have several options for this owner address setting.

1. Use an EOA account at the beginning, and change it to a contract address later. @steven1227 thinks this is a bit risky and suggests we just use a contract address from the beginning, so there will not be a single EOA can control the bridge at any time;
2. Use a multi-sig contract. We are now trying to use [Gnosis Safe](https://github.com/safe-global/safe-wallet-web) and deploy contracts and tools on T4, but we haven't succeeded yet;
3. Use Governance vote. If we cannot have multi-sig tools before mainnet launch, how about using [GovernanceVote](https://github.com/bane-labs/go-ethereum/blob/bane-main/contracts/solidity/base/GovernanceVote.sol)? By inheriting and using the `needVote` modifier, we can have a simi-multi-sig thing in bridge management.

Well, I know using `GovernanceVote` may change our genesis allocation, but how about this idea?

Just for case.

**Comment by mialbu** [comment]
To be really honest, I don't think it's a good idea to introduce additional complexity so close to mainnet.

If you can't succeed with GnosisSafe until mainnet I think it's still better to go with an EOA as owner initially. Once you're set with a Gnosis Safe, the EOA can issue a single transaction transferring the ownership:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/19a657bef8354f2a655900654955739b70dfbde9/contracts/access/Ownable2Step.sol#L41C14-L41C31

and then we execute an immediate follow-up transaction through the Gnosis safe that accepts the ownership:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/19a657bef8354f2a655900654955739b70dfbde9/contracts/access/Ownable2Step.sol#L58

**Comment by txhsl** [comment]
> If you can't succeed with GnosisSafe until mainnet I think it's still better to go with an EOA as owner initially. Once you're set with a Gnosis Safe, the EOA can issue a single transaction transferring the ownership:

I know your concern, and I'm with that as well. But @steven1227 insists that we should have another solution, and I'm working on it.

**Comment by steven1227** [comment]
> To be really honest, I don't think it's a good idea to introduce additional complexity so close to mainnet.
> 
> If you can't succeed with GnosisSafe until mainnet I think it's still better to go with an EOA as owner initially. Once you're set with a Gnosis Safe, the EOA can issue a single transaction transferring the ownership:
> 
> https://github.com/OpenZeppelin/openzeppelin-contracts/blob/19a657bef8354f2a655900654955739b70dfbde9/contracts/access/Ownable2Step.sol#L41C14-L41C31
> 
> and then we execute an immediate follow-up transaction through the Gnosis safe that accepts the ownership:
> 
> https://github.com/OpenZeppelin/openzeppelin-contracts/blob/19a657bef8354f2a655900654955739b70dfbde9/contracts/access/Ownable2Step.sol#L58

The risk now comes to this EOA then, and from what I expect now is it can not be fixed in a short time. Not acceptable.

**Comment by mialbu** [comment]
@txhsl Can you quickly explain the solution for this here? Then we can close this issue.

**Comment by mialbu** [comment]
As far as I understood, this new contract `CommitteeMultiSig` will be the owner of the bridge contract and thus the Neo X committee will be in charge of assigning roles.

Is this statement correct, @txhsl?

**Comment by steven1227** [comment]
> @txhsl Can you quickly explain the solution for this here? Then we can close this issue.

Solution is https://github.com/bane-labs/go-ethereum/pull/279 , use Governance vote

**Comment by txhsl** [comment]
We add a voteable contract at `0x1212000000000000000000000000000000000007`, which only has the following logic currently.

```solidity
// Execute an operation that calls a function on the `target` contract
function execute(
    address target,
    bytes calldata data
)
    external
    needVote(keccak256(abi.encode(target)), keccak256(abi.encode(data)))
    returns (bytes memory returndata)
{
    returndata = Address.functionCall(target, data);
}
```

> As far as I understood, this new contract CommitteeMultiSig will be the owner of the bridge contract and thus the Neo X committee will be in charge of assigning roles.

Yes.

**Comment by mialbu** [comment]
The native `CommitteeMultiSig` is used for the owner role (see [here](https://github.com/bane-labs/go-ethereum/pull/279)).
