### ISSUE TITLE
NBE-14 - Lack of neoXToken Verification

### ISSUE THREAD

**Issue by mialbu** [bane-labs/bridge-evm-contracts#186]
The `BridgeStorage` contract does not perform any check to verify that the `neoXToken` token
exists in any of the internal methods `setTokenWithdrawalFee`, `setTokenMinWithdrawalAmount`,
`setTokenMaxWithdrawalAmount`, `_setMaxTokenDeposits`.

These methods are called by the corresponding public methods of the `BridgeImpl` contract,
where the previously mentioned lack of verifications is also observed. This allows the governor
to set different values for non-existent tokens.

**Recommendation**

Check that the token referenced by the `_neoXToken` argument exists before setting the
corresponding values.

**Source Code References**
- https://github.com/bane-labs/bridge-evm-contracts/blob/0e3ad1c40c10877e5446ba350a09207cc08bea5b/contracts/bridge/BridgeStorage.sol#L248-L276
- https://github.com/bane-labs/bridge-evm-contracts/blob/0e3ad1c40c10877e5446ba350a09207cc08bea5b/contracts/bridge/BridgeImpl.sol#L545-L595

**Comment by mialbu** [comment]
Duplicate of #159

This issue  has already been fixed some time ago in commit 264dbd005792e91294b7a1f3fee6ac0badc29dec in the PR https://github.com/bane-labs/bridge-evm-contracts/pull/172.

I have introduced a modifier `onlyIfTokenRegistered(address _neoXToken)` and added the modifier to the functions where necessary.

https://github.com/bane-labs/bridge-evm-contracts/blob/a1911f73ceba8b339bc9019bbb03255f9b30f1cf/contracts/bridge/BridgeStorage.sol#L93-L97

@shargon please confirm that this issue will be marked as fixed in the report.

**Comment by shargon** [comment]
Marked as fixed.
