### ISSUE TITLE
Discussion: change Validator/Relay addresses

### ISSUE THREAD

**Issue by gsmachado** [bane-labs/bridge-evm-contracts#31]
What would be the approach if validator and/or relayer addresses need to be changed?

Hard fork? Or a management contract?

**Comment by mialbu** [comment]
This should be covered in #35.

I've talked with @steven1227 about this quite some time ago. The outcome was that updating/changing the relayer or a validator should not be a reason to fork the whole chain.

If you'd like further discussing this topic, please just reopen it.
