### ISSUE TITLE
Define initial GAS allocation for Bridge

### ISSUE THREAD

**Issue by mialbu** [bane-labs/bridge-evm-contracts#37]
With the discussion of making the bridge contract updatable, we'll need to define the design of the initial GAS allocation.

Making the contract updatable will include a proxy contract. Hence the bridge contract cannot be the one holding the entire allocation, unless there's a mechanism to reallocate it to the new contract once "updated".

**Comment by mialbu** [comment]
We'll not have an updatable contract for the v1 testnet. Thus, for v1 testnet, the initial allocation of GAS will just be held by the bridge contract.

~Once we're designing the contract update structure for the bridge contract, this needs to be defined again, since the bridge contract cannot hold the initial allocation.~ This statement is incorrect.

**Comment by mialbu** [comment]
The proxy can hold the initial balance. There's also the option to introduce a treasury contract that holds the total  initial genesis allocation (besides some needed allocation for bridge relayer, etc.).

**Comment by mialbu** [comment]
@steven1227 we'll need to discuss the approach for this for T4.

**Comment by steven1227** [comment]
use Treasury contract would be better

**Comment by mialbu** [comment]
This has been addressed in https://github.com/bane-labs/go-ethereum/pull/184.
