### ISSUE TITLE
NBE-01 - Hardcoded Signature Requirement `[Medium]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#48]
<p>The <code>verifyValidatorSignatures</code> method defines in a hardcoded manner the number of existing validators and the number of signatures required for their validation, ignoring those established during the construction of the contract.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/13f3b1d0-1b59-4ee2-9f3d-1c1ded4e840c)
<p>This implies that if, for example, 3 validators are defined during its deployment, the contract is automatically denied, since it will require 5 signatures to be correctly verified.</p>

**Remediation:**
<ul><li><p>It is necessary to obtain the mentioned values ​​from those existing in the state variables: <code>validators</code> and <code>requiredValidatorSignaturesForDeposit</code>.</p></li></ul>

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L195-L196">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L195-L196</a></p>
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L204">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L204-L213</a></p>

**Comment by mialbu** [comment]
This was partly addressed some time ago, while completely resolved by fdae4a2 now.

**Comment by mialbu** [comment]
This has been resolved.
