### ISSUE TITLE
NBE-02 - Contracts Management Risks `[Low]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#49]
<p>The logical design of the <code>BridgeContract</code> contract introduces certain minor risks that should be reviewed and considered for their improvement.<br/></p>
<h4>Emergency ERC20 Token Sending</h4><p>Even though this logic is intentional, it is necessary to mention that the ERC20 tokens received by the contract cannot be returned or transferred by the validators or the <code>governor</code>. Adding an emergency sending functionality for ERC20 tokens in this contract, which is intended only to manage the native token, can be a good practice in order to be able to return tokens incorrectly sent to the contract by users.</p><h4>Hardcoded Values</h4><p>It should be noted that the data of the <code>validators</code>, <code>relayer</code>, <code>owner</code>, <code>governor</code>, <code>securityGuard</code>, as well as those related to the limits of deposits or required signatures cannot be modified, it is necessary to be able to modify these values ​​in order to increase the resilience of the contract, deal with possible leaks of private keys or dishonest validators.</p><h4>Centralized initial values</h4><p>Although it is mentioned that the values ​​of validators must be changed during the deployment, it should be noted that the first 3 validators are the same as the <code>owner</code>, <code>governos</code> and <code>securityGuard</code>. It is advisable to ensure decentralization and separation of roles, so that validators exclusively focus on validation tasks without additional responsibilities. Appropriately separating the roles of the contract will prevent possible future problems in the contract.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/a37ae554-d9b5-487c-97a7-8f970c50e7e3)

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L13-L40">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L13-L40</a></p>

**Comment by mialbu** [comment]
> <h4>Emergency ERC20 Token Sending</h4><p>Even though this logic is intentional, it is necessary to mention that the ERC20 tokens received by the contract cannot be returned or transferred by the validators or the <code>governor</code>. Adding an emergency sending functionality for ERC20 tokens in this contract, which is intended only to manage the native token, can be a good practice in order to be able to return tokens incorrectly sent to the contract by users.</p>

Can you elaborate on this one? I don't understand it, @shargon.

---

> <h4>Hardcoded Values</h4><p>It should be noted that the data of the <code>validators</code>, <code>relayer</code>, <code>owner</code>, <code>governor</code>, <code>securityGuard</code>, as well as those related to the limits of deposits or required signatures cannot be modified, it is necessary to be able to modify these values ​​in order to increase the resilience of the contract, deal with possible leaks of private keys or dishonest validators.</p>

There is now a BridgeManagement that contains setters fore each role and the owner is allowed to and responsible for updating role assignments.

---

> <h4>Centralized initial values</h4><p>Although it is mentioned that the values ​​of validators must be changed during the deployment, it should be noted that the first 3 validators are the same as the <code>owner</code>, <code>governos</code> and <code>securityGuard</code>. It is advisable to ensure decentralization and separation of roles, so that validators exclusively focus on validation tasks without additional responsibilities. Appropriately separating the roles of the contract will prevent possible future problems in the contract.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/a37ae554-d9b5-487c-97a7-8f970c50e7e3)

These values are only used for testing purposes. By now (1fc995f9c158a9948d5c2008db9773c9c81b2bfd), each role has a different assignee for testing. There's also no role with the same assignee on testnet T3 (neither was on T2, nor will be on mainnet).

**Comment by mialbu** [comment]
> #### Emergency ERC20 Token Sending
> Even though this logic is intentional, it is necessary to mention that the ERC20 tokens received by the contract cannot be returned or transferred by the validators or the `governor`. Adding an emergency sending functionality for ERC20 tokens in this contract, which is intended only to manage the native token, can be a good practice in order to be able to return tokens incorrectly sent to the contract by users.

Just like in https://github.com/bane-labs/bridge-evm-contracts/issues/50#issuecomment-2061406932. Do you still consider the missing emergency ERC20 token a risk or can this be closed since the contract is upgradeable, what's your opinion, @shargon?

Also, the **Hardcoded Values** and **Centralized initial values** parts have been fixed. Could you mention that in the report?

**Comment by shargon** [comment]
now that is upgradeable, it's not a risk, but it will be upgraded if someone lost his money to the contract? 🤔 

I will change it to `Fixed` because upgradability change the risk to almost none.

**Comment by shargon** [comment]
@mialbu could you link me the pull request for the changes `Hardcoded Values and Centralized initial values` ?

**Comment by mialbu** [comment]
> now that is upgradeable, it's not a risk, but it will be upgraded if someone lost his money to the contract? 🤔

Good question. In any way, afaik receiving an ERC20 transfer without any function invocation does not trigger anything in the bridge contract. So, if we were to allow e.g., the governor to return such payments, how would we control the amount the governor is allowed to send back?

If you know another project that integrates such logic, could you provide me a link to it?

**Comment by mialbu** [comment]
> @mialbu could you link me the pull request for the changes `Hardcoded Values and Centralized initial values` ?

Sure, here are the commits:

- In commit 6ee92b418e200fc9e55be34aa5da3197a1c61c60 the bridge contract was changed to using a constructor. (included when merging #85)
- In commit ca0324352053ddb23f0320dfda76d836349edf62 the management contract was changed to using a constructor instead of hardcoded initial values fixing both issues mentioned (now depending on deployment/genesis storage allocation). (merged in #91)

In the tests different addresses are used for each role now as well.

**Comment by mialbu** [comment]
@shargon Can we close this issue then?

**Comment by shargon** [comment]
> @shargon Can we close this issue then?

Yes

**Comment by mialbu** [comment]
Based on the conversation above, I'm closing this issue.
