### ISSUE TITLE
NBE-05 - Outdated Compiler `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#52]
<p>Solc frequently launches new versions of the compiler. Using an outdated version of the compiler can be problematic, especially if there are errors that have been made public or known vulnerabilities that affect this version. The project has set the <code>0.8.18</code> compiler version in the config.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/4672ea97-5c2e-466d-8629-294a9262cc63)

<p>Solidity branch up to version <code>0.8.25</code>, like version <code>0.8.22</code> has important bug fixes, so it is recommended to use the most up-to-date version of pragma.</p>
<p>The source file requires a different compiler version than the Hardhat configuration. It is advisable to unify both definitions with the latest stable version of the compiler.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/19f2a196-7c33-4c7b-86a1-022932c45f45)

**Remediation:**
<ul><li><p>It is always a good policy to use the most up to date version of the pragma.</p></li></ul>

**References:**
- https://github.com/ethereum/solidity/blob/develop/Changelog.md

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/hardhat.config.ts#L10">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/hardhat.config.ts#L10</a></p>
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L2">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L2</a></p>

**Comment by mialbu** [comment]
This has been addressed in 53b0f3e67ad400edf4eb5b9413950ab943ea86d3.
@shargon

**Comment by mialbu** [comment]
This has been resolved. I'll close this issue.
