### ISSUE TITLE
NBE-06 - Outdated third-party libraries `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#53]
<p>The hardhat project used contains dependencies marked as vulnerable according to the result of the <code>npm audit</code> analysis. This does not imply a vulnerability by itself, but it does imply that an update of third-party packages or libraries is not carried out.</p>

```
# npm audit report

follow-redirects  <=1.15.5
Severity: moderate
Follow Redirects improperly handles URLs in the url.parse() function - https://github.com/advisories/GHSA-jchw-25xp-jwwc
follow-redirects' Proxy-Authorization header kept across hosts - https://github.com/advisories/GHSA-cxjh-pqwp-8mfp

undici  <=5.28.3
Undici proxy-authorization header not cleared on cross-origin redirect in fetch - https://github.com/advisories/GHSA-3787-6prv-h9w3
Undici's fetch with integrity option is too lax when algorithm is specified but hash value is in incorrect - https://github.com/advisories/GHSA-9qxr-qj54-h672
Undici's Proxy-Authorization header not cleared on cross-origin redirect for dispatch, request, stream, pipeline - https://github.com/advisories/GHSA-m4v8-wqvr-p9f7

2 vulnerabilities (1 low, 1 moderate)
```

**Remediation:**
<ul><li><p>Delete unused dependencies in the project.</p></li><li><p>Update the libraries to the most recent version.</p></li></ul>

**Comment by mialbu** [comment]
This has been addressed and will be kept in mind after https://github.com/bane-labs/bridge-evm-contracts/commit/6a5d43a63943e1a12661ced851e41a3b17ee392f.
@shargon

**Comment by mialbu** [comment]
This has been resolved. I'll close this issue.
