### ISSUE TITLE
NBE-07 - GAS Optimization `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#54]
<p>Software optimization is the process of modifying a software system to make an aspect of it work more efficiently or use less resources. This premise must be applied to smart contracts as well, so that they execute faster or in order to save GAS.</p><p>On EVM blockchain, GAS is an execution fee which is used to compensate miners for the computational resources required to power smart contracts. If the network usage is increasing, so will the value of GAS optimization.</p><p>These are some of the requirements that must be met to reduce GAS consumption:</p><ul><li><p>Short-circuiting.</p></li><li><p>Remove redundant or dead code.</p></li><li><p>Delete unnecessary libraries.</p></li><li><p>Explicit function visibility.</p></li><li><p>Use of proper data types.</p></li><li><p>Use hard-coded constant instead of state variables.</p></li><li><p>Avoid expensive operations in a loop.</p></li><li><p>Pay special attention to arithmetical operations and comparisons.</p></li></ul>
<h4>Logic Optimization</h4><p>The condition of the <code>deposit</code> method relative to the beginning of the first stored nonce is double-checked in the next call to <code>subsequentNonces</code>. Therefore, it can be safely removed.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/fbff807e-adba-4b02-8e9f-ad86c8cdc74c)

<h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L97-L100" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L97-L100</a></p></li></ul><h4>Dead Code</h4><p>In programming, a part of the source code that is never used is known as dead code. The execution of this type of code consumes more GAS during deployment in something that is not necessary.</p><p><br/>Values ​​related to the <code>owner</code>, or <code>onlyowner</code> modifier, are not used and can be removed from the contract.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L237-L240" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L237-L240</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L38" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L38</a></p></li></ul><h4>Use Custom Errors Instead of Require</h4><p>Solidity <strong>0.8.4</strong> introduced custom errors, a more efficient way to notify users of an operation failure.</p><p>It has been verified that the <code>BridgeContract</code> contract is managing the error messages through the <code>require</code> command. This instruction is more expensive than the use of custom errors because it requires placing the error message on the stack, whether or not the transaction is reverted in addition to being more susceptible to using long error messages that will produce a higher cost of gas, regardless of the result of the condition.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/2cd33df7-ba46-4317-9940-c997a0dc05a8)

<p><em>Custom errors</em> are more gas efficient than revert strings in terms of deployment and runtime cost when the revert condition is met. In order to save gas it is recommended use custom errors instead of revert strings.</p><p>The new custom errors are defined through the <code>error</code> statement, and they can also receive arguments. As indicated in the following example:</p>

```
error Unauthorized();
error InsufficientPrice(uint256 available, uint256 required);
```

<p>Afterwards, it is enough to just call them when needed using <code>if</code> conditionals:</p>

```
if (msg.sender != owner) revert Unauthorized();
```

```
if (amount > balance[msg.sender]) {
            revert InsufficientPrice({
                available: balance[msg.sender],
                required: amount
            });
}
```

<h5>References</h5><ul><li><p>https://blog.soliditylang.org/2021/04/21/custom-errors</p></li></ul><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L92-L109" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L92-L109</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L223-L243" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L223-L243</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L256" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L256</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L273-L286" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L273-L286</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L345" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L345</a></p></li></ul><h4>Redundant Code</h4><p>The <code>computeNewRoot</code> method and the <code>computeNewWithdrawalRoot</code> method share the same logic, arguments and return, it is convenient to unify both calls to reduce the bytecode size.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L318" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L318</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L169" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L169</a></p></li></ul><h4>Caching Arrays Length in Loops</h4><p>Every time an array iteration occurs in a loop, the solidity compiler will read the array's length. Thus, this is an additional <code>sload</code> operation for storage arrays (100 more extra gas for each iteration except for the first) and an additional <code>mload</code> action for memory arrays (3 additional gas for each iteration except for the first).</p>

```
for (uint i; i < array.length; ++i) {
    // ...
}
```

<p>The array length (in stack) might be cached to reduce these additional costs:</p>

```
uint length = array.length;
for (uint i; i < length; ++i) {
    // ...
}
```

<p><br/>The <code>sload</code> or <code>mload</code> action is only performed once in the example above before being replaced by the inexpensive <code>dupX</code> instruction.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L121" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L121</a></p></li></ul><h4>Optimize Require Messages</h4><p>Ethereum Virtual Machine operates under a 32-byte word memory model where an additional gas cost is paid by any operation that expands the memory that is in use.</p><p>Therefore, exceeding error messages of this length means increasing the number of slots necessary to process the require, reducing the error messages to 32 bytes or less would lead to saving gas.</p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L99" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L99</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L103" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L103</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L97-L108" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L108</a></p></li></ul><h4>Storage Optimization</h4><p>It has been detected that the mappings <code>claimableAmount</code> and <code>claimableTo</code> are always modified and queried at the same time. Therefore, using a common structure is convenient in terms of gas savings.</p>

```
struct ClaimData {
    address payable to;
    uint64 amount;
}

mapping(uint64 => ClaimData) public claimable;
```

<h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L254-L259" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L254-L259</a></p></li></ul><p></p><p>The use of the <code>immutable</code> (<a href="https://docs.soliditylang.org/en/v0.8.25/contracts.html#immutable" rel="noopener noreferrer nofollow" target="_blank">https://docs.soliditylang.org/en/v0.8.25/contracts.html#immutable</a>) keyword is recommended to obtain less expensive executions, by having the same behavior as a constant. However, by defining its value in the constructor we have a significant save of GAS. </p><h5>Source Code References</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L13-L26" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L13-L26</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L38" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L34-L35</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L38" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L38-L40</a></p></li></ul>

**Comment by mialbu** [comment]
- [x] #60
- [x] #62
- [x] #61 
- [x] #63 
- [x] #64
- [x] #65 
- [x] #66

**Comment by mialbu** [comment]
All of the issues raised here have been resolved. I'll close this issue.
