### ISSUE TITLE
NBE-08 - Solidity literals `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#55]
<p>In order to make the code easier to read and to minimize human errors, Solidity recommends the use of literals which consequently makes it more user friendly.</p><p>In the case of <code>BridgeContract</code>, the <code>10**10</code> operation is frequently used to add or eliminate the decimal difference between gas and ether. This multiplication can be avoided by using the literal <code>1e10</code>.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/3d761b9b-a101-4d43-b8ea-5b0b3a69208a)

**References:**
- https://docs.soliditylang.org/en/latest/units-and-global-variables.html#units-and-globally-available-variables

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L335">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L335</a></p>
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L330">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L330</a></p>
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L276">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L276</a></p>

**Comment by mialbu** [comment]
Solidity literals are used where applicable since [this commit](https://github.com/bane-labs/bridge-evm-contracts/commit/746f15126ef3a85b4b16703eb49b41192591af64). I'll close this issue.
