### ISSUE TITLE
NBE-10 - Improvable Code Quality `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#57]
<p>It has been possible to verify that there is a lack of order and structure in the code, making it challenging to read and analyze. For example: variable order, mapping, among others. This is not a vulnerability by itself, but it helps to improve the code and reduces the appearance of new vulnerabilities.</p><p>High-quality code is important for various reasons, including maintainability, reliability, efficiency, scalability, and security. Well-written code that adheres to best practices offers several advantages, such as easier to maintain and extend, less prone to errors, more efficient, improved collaboration potential, scalability, and heightened security. Ultimately, good code quality contributes to a more dependable, maintainable, and secure software product, improving the overall user experience while reducing the risk of introducing new vulnerabilities.</p>
<h4>Use Constructor to Define Values</h4><p>The <code>BrigeContract</code> contract requires its correct configuration for its correct use, however, it is mentioned that the values ​​must be modified manually prior to deployment, instead of defining them in the contract constructor, as is usual, in this way not only human errors will be avoided during the deploy process, and the source code will also be compared against similar ones in browsers and its maintenance and testing will be improved.</p>

```
// Todo: Before compiling byte code for genesis script, make sure to set the correct values for the following variables:
// - relayer
// - validators
// - minWithdrawalAmount
// - maxWithdrawalAmount
// - remove the receive function as it is only used for testing purpose.
```

<h5>Source code reference</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L42-L44" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L4-L9</a></p></li></ul><h4>Lack of Comments</h4><p>The <code>deposit</code> method requires that the signatures be ordered in the same way that the validators have been stored in the array. This special case should be reflected in a comment of the <code>deposit</code> method.</p><h5>Source code reference</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L88" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L88</a></p></li></ul><h4>Good Naming</h4><p>The variable <code>hashAmount</code> of the <code>withdraw</code> method makes it appear that it is a hash, when in reality it is the value converted to 8 decimal places, it is advisable to modify the name of the variable in order to improve the readability and understanding of the method.</p><h5>Source code reference</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L289" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L289</a></p></li></ul><h4>Named Mappings</h4><p>Solidity <em>0.8.18</em> allows to use named parameters in mapping types. This new feature enables the assignment of descriptive names to mappings, improving the code's readability, interpretation, and audit process.</p><h5>Reference:</h5><ul><li><p><a href="https://soliditylang.org/blog/2023/02/01/solidity-0.8.18-release-announcement" rel="noopener noreferrer nofollow" target="_blank">https://soliditylang.org/blog/2023/02/01/solidity-0.8.18-release-announcement</a></p></li></ul><h5>Source code reference</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L42-L44" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L42-L44</a></p></li></ul><h4>Open TODO</h4><p>Certain to-do comments have been detected that reflect that the code is unfinished. Thus, many changes that have not been audited could introduce new vulnerabilities in the future.</p><h5>Source code reference</h5><ul><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L4" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L4</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L154" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L154</a></p></li><li><p><a href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L299" rel="noopener noreferrer nofollow" target="_blank">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L299</a></p></li></ul>

**Remediation:**
<p>As a reference, it is always recommendable to apply coding style/good practices that can be found in multiple standards such as:</p><ul><li><p>Solidity Style Guide” - https://docs.soliditylang.org/en/v0.8.23/style-guide.html</p></li></ul><p>These references are very useful to improve smart contract quality. Many of these practices are widely accepted and recognized as a popular and effective approach to software development.</p>

**References:**
- https://solidity.readthedocs.io/en/latest

**Comment by mialbu** [comment]
**Use Constructor to Define Values**
Using a constructor in this contract would simplify modifying contract variables in testing. However, as soon as this contract is used in production there will be no use to the constructor. It will be a native contract, meaning that a constructor would be redundant since never executed. The decision to not use a constructor for testing purposes was made in order to follow the process, so that a single deployment transaction will provide the necessary initial storage entries.

I've opened the issue #72 to consider using a constructor for testing purpose.

**Lack of Comments**
- [x] https://github.com/bane-labs/bridge-evm-contracts/issues/67

**Good Naming**
- [x] #68

**Named Mappings**
- [x] #70

**Open TODOs**
- [ ] #71

**Comment by mialbu** [comment]
> #### Use Constructor to Define Values
> The `BrigeContract` contract requires its correct configuration for its correct use, however, it is mentioned that the values ​​must be modified manually prior to deployment, instead of defining them in the contract constructor, as is usual, in this way not only human errors will be avoided during the deploy process, and the source code will also be compared against similar ones in browsers and its maintenance and testing will be improved.
> 
> ```
> // Todo: Before compiling byte code for genesis script, make sure to set the correct values for the following variables:
> // - relayer
> // - validators
> // - minWithdrawalAmount
> // - maxWithdrawalAmount
> // - remove the receive function as it is only used for testing purpose.
> ```
> 
> ##### Source code reference
> * [https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L4-L9](https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L42-L44)
> 
> #### Lack of Comments

This has been addressed. The contracts now use constructors once #91 is merged.

> #### Lack of Comments
> The `deposit` method requires that the signatures be ordered in the same way that the validators have been stored in the array. This special case should be reflected in a comment of the `deposit` method.
> 
> ##### Source code reference
> * https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L88

Done in commit f292c0bf1fd8b8274e1417d4596af52dd2f1a7b8.

> #### Good Naming
> The variable `hashAmount` of the `withdraw` method makes it appear that it is a hash, when in reality it is the value converted to 8 decimal places, it is advisable to modify the name of the variable in order to improve the readability and understanding of the method.
> 
> ##### Source code reference
> * https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L289

This has been fixed a while ago and is no longer applicable.

> #### Named Mappings
> Solidity _0.8.18_ allows to use named parameters in mapping types. This new feature enables the assignment of descriptive names to mappings, improving the code's readability, interpretation, and audit process.
> 
> ##### Reference:
> * https://soliditylang.org/blog/2023/02/01/solidity-0.8.18-release-announcement
> 
> ##### Source code reference
> * https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L42-L44

This has been addressed and is being followed with the latest changes in commit dd999d58417acfc2954b436a219dd8ce89696cfe.

> #### Open TODO
> Certain to-do comments have been detected that reflect that the code is unfinished. Thus, many changes that have not been audited could introduce new vulnerabilities in the future.
> 
> ##### Source code reference
> * https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L4
> * https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L154
> * https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L299

The todos have all been resolved.
