### ISSUE TITLE
NBE-11 - Lack of Event Index `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#58]
<p>Event indexing of smart contracts can be used to filter during the querying of events. This can be very useful when making DApps or in the off-chain processing of the events in our contract, as it allows filtering by specific addresses, making it much easier for developers to query the results of invocations.</p>

**Remediation:**
<ul><li><p>It could be convenient to review the <code>BridgeContract</code> contract to ensure that all the events have the necessary indexes for the correct functioning of the possible DApps. Addresses are usually the best argument to filter an event. </p></li><li><p>It is advisable to add index in the <code>to</code> field of the events: <code>Deposit</code>, <code>Claimable</code> and <code>Claimed</code>.</p></li></ul>

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L48-L51">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L48-L51</a></p>

**Comment by mialbu** [comment]
Indexes are now widely used in events. I'll close this issue.
